INSERT INTO public.site_content (key, value) VALUES
('hero_subtitle','We connect talented youths with meaningful opportunities to learn, build and grow together.'),
('home_who_eyebrow','WHO WE ARE'),
('home_who_title','Empowering Youths Through Actions'),
('home_who_description','We create space for young people to build real skills through collaboration, mentorship and hands-on projects.'),
('home_who_cta_label','Learn More'),
('home_feature1_title','Skill Development'),
('home_feature1_description','Access training programs to level up your skills'),
('home_feature2_title','Collaborative Projects'),
('home_feature2_description','Join forces with others to solve problems and create impact'),
('home_feature3_title','Leadership'),
('home_feature3_description','Lead initiatives and grow as future leaders'),
('home_feature4_title','Community Impacts'),
('home_feature4_description','Contribute to change through meaningful actions'),
('home_events_title','Upcoming Events'),
('home_projects_title','Projects Published'),
('about_title','About YOUTHs'),
('about_paragraph1','YOUTHs is a youth-driven community turning creativity and ambition into real opportunities.'),
('about_paragraph2','We bring together designers, developers and organisers to deliver professional work while learning from each other.'),
('about_image_url','/Bwtnd.png'),
('about_quote_words','LEARN, BUILD, COLLABORATE, EARN'),
('about_mission_title','Our Mission'),
('about_mission_text','To empower talented youth by connecting them with meaningful opportunities, delivering professional digital and creative services, and fostering growth through collaboration, technology, and fair recognition.'),
('about_vision_title','Our Vision'),
('about_vision_text','To become a globally recognized youth-driven talent ecosystem that transforms creativity and innovation into sustainable opportunities and positive impact.'),
('about_values_title','Our Values'),
('about_values_list','Respect Clients & Commitments, Real Skills Building, Responsibility, Collaboration, Innovation, Integrity, Fairness, Quality, Growth'),
('about_grow_heading1','Learn & Grow'),
('about_grow_heading2','With YOUTHs'),
('about_grow_description','Join workshops, real client projects and a community that helps you level up every month.'),
('about_grow_image_url','/Y6kHUB.png'),
('activities_past_title','Past Activities'),
('activities_upcoming_title','Upcoming Activities'),
('activities_register_label','Register Now'),
('events_upcoming_title','Upcoming Events')
ON CONFLICT (key) DO NOTHING;