// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezbybgyqnivmskneurqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6YnliZ3lxbml2bXNrbmV1cnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUzMDAwODEsImV4cCI6MjEwMDg3NjA4MX0.LhqjjyfNVlbvdk9h6XRWsNyBLkwLsw1_IDR6YU7tQP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});